export const PARAMETER_STORE_CONFIG_PROPERTIES: string = "PARAMETER_STORE_CONFIG_PROPERTIES";
export const PARAMETER_STORE_CONFIG_PARAMETERS: string = "PARAMETER_STORE_CONFIG_PARAMETERS";
export const PARAMETER_STORE_SSM_CLIENT: string = "PARAMETER_STORE_SSM_CLIENT";
