export const PARAMETER_STORE_CONFIG_PROPERTIES = Symbol("PARAMETER_STORE_CONFIG_PROPERTIES");
export const PARAMETER_STORE_CONFIG_PARAMETERS = Symbol("PARAMETER_STORE_CONFIG_PARAMETERS");
export const PARAMETER_STORE_SSM_CLIENT = Symbol("PARAMETER_STORE_SSM_CLIENT");
